name: Delete Old Releases

on:
  schedule:
  - cron: "45 23 * * 1"
  workflow_dispatch:

jobs:
  trim:
    name: "Delete old tags"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Delete Old Tags
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: bash ./delete_tags.sh
